[orca]
# see https://www.orcasoftware.de/tutorials_orca/first_steps/parallel.html
cmd = '/groups/kemi/julius/opt/orca_5_0_4_linux_x86-64_shared_openmpi411/orca'
setenv = 'env - PATH="/groups/kemi/julius/opt/orca_5_0_4_linux_x86-64_shared_openmpi411:/software/kemi/openmpi/openmpi-4.1.1/bin:$PATH" LD_LIBRARY_PATH="/groups/kemi/julius/opt/orca_5_0_4_linux_x86-64_shared_openmpi411:/software/kemi/openmpi/openmpi-4.1.1/lib:$LD_LIBRARY_PATH"'

[xtb]
cmd = "xtb"

[gausian]
gauxtb = "/groups/kemi/julius/opt/xtb_gaussian/xtb_external.py gbsa=methanol"
